# Generated by Django 3.0.1 on 2020-12-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, null=True)),
                ('work', models.CharField(blank=True, default='studiant', max_length=255)),
                ('linkedin_link', models.URLField(blank=True, max_length=255)),
                ('instagram_link', models.URLField(blank=True, max_length=255)),
                ('facebook_link', models.URLField(blank=True, max_length=255)),
                ('youtube_link', models.URLField(blank=True, max_length=255)),
                ('twitter_link', models.URLField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
            ],
        ),
    ]
