# Generated by Django 3.0.1 on 2020-12-19 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, null=True)),
                ('work', models.CharField(blank=True, default='studiant', max_length=255)),
                ('linkedin_link', models.URLField(blank=True, max_length=255)),
                ('instagram_link', models.URLField(blank=True, max_length=255)),
                ('facebook_link', models.URLField(blank=True, max_length=255)),
                ('youtube_link', models.URLField(blank=True, max_length=255)),
                ('twitter_link', models.URLField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
