# Generated by Django 3.0.1 on 2020-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201220_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='prof_views',
            field=models.IntegerField(default=0),
        ),
    ]
