# Generated by Django 3.1.3 on 2020-12-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_prof_prof_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='phone',
            field=models.IntegerField(blank=True, max_length=70, null=True),
        ),
    ]
