# Generated by Django 3.1.3 on 2020-12-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_prof_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
