# Generated by Django 3.1.3 on 2020-12-22 19:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201222_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='phone',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
