# Generated by Django 3.1.3 on 2020-12-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201222_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
