# Generated by Django 3.1.3 on 2020-12-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201222_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
